<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, dirección, tlf, email, edad, estado_civil)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dirección (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT estado_civil (#PCDATA)>
]>
<agenda>
<contacto>
<nombre>Abel</nombre>
<dirección>Calle Barco</dirección>
<tlf>12345678</tlf>
<email>abelmillanrodriguez1@gmail.com</email>
<edad>19</edad>
<estado_civil>soltero</estado_civil>
</contacto>
</agenda>
